image: Visual Studio 2022

before_build:
  - dotnet restore "Assets Editor/Assets Editor.sln"

build_script:
  - dotnet publish "Assets Editor\Assets Editor.sln" -c Release -r win-x64 --self-contained false -o publish

artifacts:
  - path: publish\**
    name: AssetsEditor
